In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
def day(date):
    return date.split('/')[1]
def month(date):
    return date.split('/')
def plotter(data,app):
        data["Day"]=data["EXEDATE"].apply(day)
        data["Month"]=data["EXEDATE"].apply(month)
        dict1={'Pass':1,"Fail":0}

        dict2={'End to End':1, 'Cart Updation':2, 'Tag':3, 'login':4, 'Custom Badging':5,
       'Subscribe':6, 'Register':7, 'Promo':8, 'Badging':9, 'Unsubscribe':10}
        dict3={'Data':1, 'Environment':2, '0.0':0, 'Requirement':3, 'Functional':4}
        data["mSTATUS"]=data["STATUS"].map(dict1)
        data["mFunction"]=data["Function"].map(dict2)
        data["mDefect"]=data["Defect"].map(dict3)
        data1=pd.read_csv("future.csv")
 
        x=data[data.AppName=="OnePlan"][["Day","Month","Day Weight"]]
        y=data[data.AppName=="OnePlan"]["mSTATUS"]
        
        
        week_weight={"Sunday":4,"Monday":1,"Tuesday":1,"Wednesday":1,"Thursday":1,"Friday":3,"Saturday":3}
        data1["mWeekDay"]=data1["WeekDay"].map(week_weight)
        
        special_weight={"Christmas":6,"Haloween":4,"Independence Day":4,"New Year":5,"Thanksgiving Week":6}
        data1["mSpecial"]=data1["Special"].map(special_weight)
        data1=data1.fillna(0)
        
        l=len(data1)
        for i in range(l):
            data1.iloc[i,4]=data1.iloc[i,5]+data1.iloc[i,6]
       
        x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
        data1["Day"]=data["EXEDATE"].apply(day)
        data1["Month"]=data["EXEDATE"].apply(month)
        clf = DecisionTreeClassifier(max_depth=500)
        
        clf = clf.fit(x_train,y_train)
        y_pred = clf.predict(x_test)
        data1["mSTATUS"]=y_pred
        revdict={1:"Pass",0:"Fail"}
        data1["STATUS"]=data1["mSTATUS"].map(revdict)
        data=data.set_index(["AppName","EXEDATE"])
        data1=data1.set_index("EXEDATE")
        plt.figure(figsize=(150,15))
        plt.plot(data.loc[("OnePlan",),"STATUS"],color="black")
        plt.plot(data1.loc[:,"STATUS"],color="blue")
        plt.xticks(rotation=90)
        plt.savefig('report/'+app+'.pdf')
                
        
plotter(pd.read_csv("updated_final.csv"),"DNM")

ValueError: setting an array element with a sequence.

In [31]:
import pandas as pd
import numpy as np

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

In [33]:
def day(date):
    return date.split('/')[1]
def month(date):
    return date.split('/')[0]

In [34]:
data=pd.read_csv("updated_final.csv")

In [35]:
data["Day"]=data["EXEDATE"].apply(day)
data["Month"]=data["EXEDATE"].apply(month)
dict1={'Pass':1,"Fail":0}

In [36]:
dict2={'End to End':1, 'Cart Updation':2, 'Tag':3, 'login':4, 'Custom Badging':5,'Subscribe':6, 'Register':7, 'Promo':8, 'Badging':9, 'Unsubscribe':10}
dict3={'Data':1, 'Environment':2, '0.0':0, 'Requirement':3, 'Functional':4}
data["mSTATUS"]=data["STATUS"].map(dict1)
data["mFunction"]=data["Function"].map(dict2)
data["mDefect"]=data["Defect"].map(dict3)
data1=pd.read_csv("future.csv")

In [37]:
x=data[data.AppName=="OnePlan"][["Day","Month","Day Weight"]]
y=data[data.AppName=="OnePlan"]["mSTATUS"]

In [38]:
week_weight={"Sunday":4,"Monday":1,"Tuesday":1,"Wednesday":1,"Thursday":1,"Friday":3,"Saturday":3}
data1["mWeekDay"]=data1["WeekDay"].map(week_weight)
        
special_weight={"Christmas":6,"Haloween":4,"Independence Day":4,"New Year":5,"Thanksgiving Week":6}
data1["mSpecial"]=data1["Special"].map(special_weight)
data1=data1.fillna(0)

In [39]:
data1

        EXEDATE  STATUS    WeekDay   Special  Day Weight  mWeekDay  mSpecial
0      1/1/2019     0.0    Tuesday  New Year         0.0         1       5.0
1      1/2/2019     0.0  Wednesday         0         0.0         1       0.0
2      1/3/2019     0.0   Thursday         0         0.0         1       0.0
3      1/4/2019     0.0     Friday         0         0.0         3       0.0
4      1/5/2019     0.0   Saturday         0         0.0         3       0.0
..          ...     ...        ...       ...         ...       ...       ...
360  12/27/2019     0.0     Friday         0         0.0         3       0.0
361  12/28/2019     0.0   Saturday         0         0.0         3       0.0
362  12/29/2019     0.0     Sunday         0         0.0         4       0.0
363  12/30/2019     0.0     Monday         0         0.0         1       0.0
364  12/31/2019     0.0    Tuesday         0         0.0         1       0.0

[365 rows x 7 columns]

In [40]:
data

,AppName,TCID,STATUS,EXEDATE,ENV|CODE|DATA|REQ,TestCaseID,WeekDay,Special,Day Weight,Function,Defect,mWeekDay,mSpecial,Day,Month,mSTATUS,mFunction,mDefect
0,OnePlan,1,Fail,1/1/2016,PROD2.0|import plotly|The plotly.plotly module...,10001,Friday,New Year,3,End to End,Data,3,5,1,1,0,1,1.0
1,OnePlan,2,Fail,1/2/2016,STG2.0|for x in range(10)|List out of index [1...,10002,Saturday,0,3,Cart Updation,Environment,3,0,2,1,0,2,2.0
2,OnePlan,3,Fail,1/3/2016,PROD2.0|Not compatible with IOS 13|Update not ...,10003,Sunday,0,4,Tag,Data,4,0,3,1,0,3,1.0
3,OnePlan,4,Pass,1/4/2016,0,10004,Monday,0,1,login,0,1,0,4,1,1,4,NaN
4,OnePlan,5,Pass,1/5/2016,0,10005,Tuesday,0,1,Custom Badging,0,1,0,5,1,1,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10955,WFM,361,Pass,12/27/2018,0,20956,Friday,0,3,Cart Updation,0,3,0,27,12,1,2,NaN
10956,WFM,362,Fail,12/28/2018,"STG2.0|for i,j in range()|range expected 1 arg...",20957,Saturday,0,3,Cart Updation,Requirement,3,0,28,12,0,2,3.0
10957,WFM,363,Fail,12/29/2018,"DEV2.0|for val in ""string"": |val : undefined v...",20958,Sunday,0,4,Tag,Environment,4,0,29,12,0,3,2.0
10958,WFM,364,Fail,12/30/2018,STG2.0|import matplotlib.pyplot as plt|matplot...,20959,Monday,0,1,Tag,Data,1,0,30,12,0,3,1.0
10959,WFM,365,Pass,12/31/2018,0,20960,Tuesday,0,1,Cart Updation,0,1,0,31,12,1,2,NaN

In [41]:
l=len(data1)
for i in range(l):
            data1.iloc[i,4]=data1.iloc[i,5]+data1.iloc[i,6]

In [42]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [43]:
x_train

     Day Month  Day Weight
160    9     6           1
3796  17     5           4
7451  22     5           1
7648   5    12           1
7336  27     1           3
...   ..   ...         ...
7426  27     4           1
4009  16    12           1
7484  24     6           3
235   23     8           1
7640  27    11           1

[767 rows x 3 columns]